# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'harvsearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmSearch(object):
    def setupUi(self, frmSearch):
        frmSearch.setObjectName("frmSearch")
        frmSearch.resize(269, 166)
        self.widget = QtWidgets.QWidget(frmSearch)
        self.widget.setGeometry(QtCore.QRect(60, 130, 195, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSearchOK = QtWidgets.QPushButton(self.widget)
        self.btnSearchOK.setObjectName("btnSearchOK")
        self.horizontalLayout.addWidget(self.btnSearchOK)
        self.btnSearchCancel = QtWidgets.QPushButton(self.widget)
        self.btnSearchCancel.setObjectName("btnSearchCancel")
        self.horizontalLayout.addWidget(self.btnSearchCancel)
        self.widget1 = QtWidgets.QWidget(frmSearch)
        self.widget1.setGeometry(QtCore.QRect(10, 11, 241, 107))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineSubSearch = QtWidgets.QLineEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSubSearch.sizePolicy().hasHeightForWidth())
        self.lineSubSearch.setSizePolicy(sizePolicy)
        self.lineSubSearch.setBaseSize(QtCore.QSize(0, 0))
        self.lineSubSearch.setObjectName("lineSubSearch")
        self.verticalLayout.addWidget(self.lineSubSearch)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cmbSearchTime = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSearchTime.sizePolicy().hasHeightForWidth())
        self.cmbSearchTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmbSearchTime.setFont(font)
        self.cmbSearchTime.setObjectName("cmbSearchTime")
        self.cmbSearchTime.addItem("")
        self.cmbSearchTime.addItem("")
        self.cmbSearchTime.addItem("")
        self.cmbSearchTime.addItem("")
        self.cmbSearchTime.addItem("")
        self.verticalLayout.addWidget(self.cmbSearchTime)

        self.retranslateUi(frmSearch)
        QtCore.QMetaObject.connectSlotsByName(frmSearch)

    def retranslateUi(self, frmSearch):
        _translate = QtCore.QCoreApplication.translate
        frmSearch.setWindowTitle(_translate("frmSearch", "Search Subscriptions"))
        self.btnSearchOK.setText(_translate("frmSearch", "OK"))
        self.btnSearchCancel.setText(_translate("frmSearch", "Cancel"))
        self.label.setText(_translate("frmSearch", "Search for:"))
        self.label_2.setText(_translate("frmSearch", "Posted when:"))
        self.cmbSearchTime.setItemText(0, _translate("frmSearch", "Any time"))
        self.cmbSearchTime.setItemText(1, _translate("frmSearch", "Last day"))
        self.cmbSearchTime.setItemText(2, _translate("frmSearch", "Last week"))
        self.cmbSearchTime.setItemText(3, _translate("frmSearch", "Last month"))
        self.cmbSearchTime.setItemText(4, _translate("frmSearch", "Last year"))
