# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'harvnewsub.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmNewSub(object):
    def setupUi(self, frmNewSub):
        frmNewSub.setObjectName("frmNewSub")
        frmNewSub.resize(280, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(frmNewSub)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(frmNewSub)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineNewSubFeedUrl = QtWidgets.QLineEdit(frmNewSub)
        self.lineNewSubFeedUrl.setClearButtonEnabled(True)
        self.lineNewSubFeedUrl.setObjectName("lineNewSubFeedUrl")
        self.verticalLayout.addWidget(self.lineNewSubFeedUrl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnNewSubCheck = QtWidgets.QPushButton(frmNewSub)
        self.btnNewSubCheck.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnNewSubCheck.setObjectName("btnNewSubCheck")
        self.horizontalLayout_2.addWidget(self.btnNewSubCheck)
        self.lblFeedValid = QtWidgets.QLabel(frmNewSub)
        self.lblFeedValid.setText("")
        self.lblFeedValid.setObjectName("lblFeedValid")
        self.horizontalLayout_2.addWidget(self.lblFeedValid)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(frmNewSub)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineNewSubTitle = QtWidgets.QLineEdit(frmNewSub)
        self.lineNewSubTitle.setObjectName("lineNewSubTitle")
        self.verticalLayout.addWidget(self.lineNewSubTitle)
        self.label_2 = QtWidgets.QLabel(frmNewSub)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listNewSubFolders = QtWidgets.QListWidget(frmNewSub)
        self.listNewSubFolders.setObjectName("listNewSubFolders")
        self.verticalLayout.addWidget(self.listNewSubFolders)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNewSubOK = QtWidgets.QPushButton(frmNewSub)
        self.btnNewSubOK.setObjectName("btnNewSubOK")
        self.horizontalLayout.addWidget(self.btnNewSubOK)
        self.btnNewSubCancel = QtWidgets.QPushButton(frmNewSub)
        self.btnNewSubCancel.setObjectName("btnNewSubCancel")
        self.horizontalLayout.addWidget(self.btnNewSubCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(frmNewSub)
        QtCore.QMetaObject.connectSlotsByName(frmNewSub)

    def retranslateUi(self, frmNewSub):
        _translate = QtCore.QCoreApplication.translate
        frmNewSub.setWindowTitle(_translate("frmNewSub", "New Subscription"))
        self.label.setText(_translate("frmNewSub", "Enter feed URL:"))
        self.btnNewSubCheck.setText(_translate("frmNewSub", "Check"))
        self.label_3.setText(_translate("frmNewSub", "Feed title:"))
        self.label_2.setText(_translate("frmNewSub", "Select folder:"))
        self.btnNewSubOK.setText(_translate("frmNewSub", "OK"))
        self.btnNewSubCancel.setText(_translate("frmNewSub", "Cancel"))
